export type ApiErrorCode =
  | 'invalid_session'
  | 'forbidden'
  | 'passage_not_found'
  | 'request_not_found'
  | 'bad_input'
  | 'allowance_exhausted'
  | 'invalid_model_answer'
  | 'dependency_failure'
  | 'http_error'
  | 'network'
  | 'protocol'
  | 'cancelled'
