// Generated by scripts/build/collectBuildStats.mjs from the git history of
// this repository. Do not edit by hand: run
// `node scripts/build/collectBuildStats.mjs` after new commits and commit the
// result. The page at /built imports this file and never reads git at runtime.
export const buildStats = {
  head: {
    hash: '0ce60d8',
    date: '2026-09-16T02:17:50+02:00',
  },
  firstCommitAt: '13 September 2026, 19:59',
  lastCommitAt: '16 September 2026, 02:17',
  elapsedHours: 54,
  calendarDays: 4,
  commitCount: 129,
  files: {
    tracked: 1662,
    source: 673,
    edge: 354,
    migrations: 16,
    tests: 104,
    docs: 39,
  },
  halfDays: [
    {
      key: '2026-09-13-pm',
      label: '13 September, after noon',
      commitCount: 8,
      firstAt: '19:59',
      lastAt: '22:59',
      scopes: ['edge 2', 'evals 2', 'docs 1', 'feat 1', 'mcp 1'],
    },
    {
      key: '2026-09-14-am',
      label: '14 September, before noon',
      commitCount: 23,
      firstAt: '00:01',
      lastAt: '11:51',
      scopes: ['docs 6', 'deploy 2', 'evals 2', 'app 1', 'build 1'],
    },
    {
      key: '2026-09-14-pm',
      label: '14 September, after noon',
      commitCount: 21,
      firstAt: '12:00',
      lastAt: '22:27',
      scopes: ['docs 7', 'research 7', 'db 3', 'browser 1', 'chore 1'],
    },
    {
      key: '2026-09-15-am',
      label: '15 September, before noon',
      commitCount: 13,
      firstAt: '01:03',
      lastAt: '11:55',
      scopes: ['workspace 4', 'ui 3', 'research 2', 'adr 1', 'auth 1'],
    },
    {
      key: '2026-09-15-pm',
      label: '15 September, after noon',
      commitCount: 33,
      firstAt: '12:03',
      lastAt: '18:31',
      scopes: ['research 4', 'ui 4', 'docs 3', 'landing 3', 'public 3'],
    },
    {
      key: '2026-09-16-am',
      label: '16 September, before noon',
      commitCount: 31,
      firstAt: '00:07',
      lastAt: '02:17',
      scopes: ['research 5', 'docs 4', 'client 2', 'corpus 2', 'db 2'],
    },
  ],
} as const
